### ISSUE TITLE
LLMA models talking gibberish

### ISSUE THREAD

**Issue by daniandtheweb** [WapaMario63/GPTQ-for-LLaMa-ROCm#2]
Using a Radeon 5700XT on Arch with any model produces completely random words as output or no output at all.

**Comment by WapaMario63** [comment]
Have you tried lowering top_p and temperature parameters? It has a higher chance of outputting gibberish if the temperature is over 1.25 in my experience. As for refusal to generate any output, llama models has the tendency to just stop after a complete sentence, especially on alpaca models, so try to give it an incomplete sentence. 
Outside of this advice of experimenting with parameters, I don't know well the inner workings of this (or know anything AI related, I don't even program in python or do GPU stuff outside of 3D graphics) as this is only a cuda kernel port.

**Comment by daniandtheweb** [comment]
It doesn't seem to be caused by any setting. From what I can see it seems to be a similar problem that the 5700 gpu suffers on stable diffusion: the inference works but the output is broken(here causes random words to appear while on stable diffusion it outputs a blank image). On stable diffusion the solution is using two parameters --no-half and --precision full, however I'm quite new to GPU programming so I don't really know how a setting like that could be applied here.

**Comment by VeryOriginalNonsense** [comment]
I've had something similar to what you describe because I was using models that where generated with a newer version of GPTQ-for-LLaMa. In particular it was because --groupsize and --act-order where used together. [This](https://huggingface.co/TheBloke/koala-13B-GPTQ-4bit-128g) is an example of what I mean.

But just like in that example, you may be able to just ignore the newer model and link an older model instead (from the same repo).

**Comment by daniandtheweb** [comment]
I tried different models generated at different times, but the result is still the same gibberish output.

**Comment by WapaMario63** [comment]
If you are using models quantized for triton, it will not work with cuda (and so too this repo) at all. If you are trying to use models recently quantized with cuda from the main GPTQ-for-LLaMa repo (which I'd like it if you linked them to test myself), try using the `rocm-latest` branch as that is meant to be in parity with the upstream `cuda` branch, which I have not tested at all. I heard said upstream cuda supports both --groupsize and --act-order, meaning that models quantized that way won't work with the main `rocm` branch.

If this is really about the RX 5000 series GPUs requiring full precision, the kernels would probably need to be modified to support that, which I would have to figure out with my lack of experience in this field or someone else does it and opens a PR, whichever comes first.

**Comment by ksylvan** [comment]
Does the `rocm-latest` branch work with torch-2.0.0? What's the breaking change with torch-2.0.0? Thank you.

**Comment by daniandtheweb** [comment]
Even using the rocm-latest branch the result is the gibberish output.

**Comment by daniandtheweb** [comment]
I'm closing the issue since the problem is probably caused by ROCm not officially supporting my specific card.
