### ISSUE TITLE
Support for splitting over VRAM and CPU RAM

### ISSUE THREAD

**Issue by Visne** [WapaMario63/GPTQ-for-LLaMa-ROCm#3]
Perhaps this is not the correct place to open this issue, but it is my understanding that with oobabooga's text-generation-webui you can pass `--auto-devices` to automatically split the model over the VRAM and RAM if the model is too big for the VRAM. If I try this however, I get the following error:

```
OutOfMemoryError: HIP out of memory. Tried to allocate 22.00 MiB (GPU 0; 15.98 GiB total capacity; 15.71 GiB already allocated; 
80.00 MiB free; 15.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to 
avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
```

Apart from that everything works great, thank you.

**Comment by WapaMario63** [comment]
`--auto-devices` does not work with GPTQ-for-LLaMa, you use `--pre_layer <number>` instead, with the number being how many layers to allocate to your GPU with the rest going to your CPU, llama 30b has a total of 60 layers for example. The performance isn't good however, worse than using llamacpp.

**Comment by Visne** [comment]
Thanks.
